packages:
  - "apps/*"
  - "deployment/"

injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
minimumReleaseAge: 1440
allowBuilds:
  '@pulumi/command': true
  esbuild: true
  protobufjs: true
  secp256k1: true
